<a href="https://colab.research.google.com/github/BigD281/DeepLearning/blob/main/Deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành Deeplearning Buổi 1


## Các bài ví dụ Numpy và pandas

In [16]:
import numpy as np
import pandas as pd
# 1. Tạo mảng cơ bản
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)

# 2. Khởi tạo mảng đặc biệt
zeros_arr = np.zeros((3, 4)) # Mảng toàn số 0
ones_arr = np.ones((2, 3, 4)) # Mảng toàn số 1
arange_arr = np.arange(10, 25, 5) # Mảng từ 10 đến 25, bước nhảy 5
linspace_arr = np.linspace(0, 2, 9) # 9 số cách đều từ 0 đến 2

# 3. Các phép toán ma trận
print("Tổng mảng a:", a.sum())
print("Giá trị nhỏ nhất mảng b:", b.min())
print("Ma trận b sau khi chuyển vị:\n", b.T)

Tổng mảng a: 6
Giá trị nhỏ nhất mảng b: 1.5
Ma trận b sau khi chuyển vị:
 [[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]


In [17]:


# 1. Tạo DataFrame từ Dictionary
data = {
    'Country': ['Belgium', 'India', 'Brazil'],
    'Capital': ['Brussels', 'New Delhi', 'Brasília'],
    'Population': [11190846, 1303171035, 207847528]
}
df = pd.DataFrame(data, columns=['Country', 'Capital', 'Population'])

# 2. Lấy thông tin cơ bản
print("3 dòng đầu tiên:\n", df.head(3))
print("Kích thước bảng:", df.shape)
print("Thông tin chung:\n", df.info())

# 3. Truy xuất dữ liệu
# Lấy theo vị trí (Hàng 0, Cột 0)
print("Phần tử đầu tiên:", df.iloc[0, 0])
# Lấy theo tên (Dòng 0, Cột Capital)
print("Thủ đô dòng đầu:", df.loc[0, 'Capital'])

3 dòng đầu tiên:
    Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528
Kích thước bảng: (3, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Country     3 non-null      object
 1   Capital     3 non-null      object
 2   Population  3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
Thông tin chung:
 None
Phần tử đầu tiên: Belgium
Thủ đô dòng đầu: Brussels


In [18]:
# Numpy sang Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print("DataFrame từ Numpy:\n", df_h)

# Pandas sang Numpy
numpy_h = df_h.to_numpy() # Cách này chuẩn hơn np.array(df_h) trong các bản mới
print("Numpy array từ DataFrame:\n", numpy_h)

DataFrame từ Numpy:
    0  1
0  1  2
1  3  4
Numpy array từ DataFrame:
 [[1 2]
 [3 4]]


## Bài tập lab 1 numpy pandas và tensor

### Numpy

In [10]:
import numpy as np
# --- BÀI 8: Tạo mảng và đổi dấu phần tử trong khoảng [9, 15] ---
print("--- Numpy Bài 8 ---")
arr_8 = np.arange(20) # Tạo mảng từ 0 đến 19 (20 phần tử)
arr_8[(arr_8 >= 9) & (arr_8 <= 15)] *= -1
print("Mảng sau khi đổi dấu:\n", arr_8)



--- Numpy Bài 8 ---
Mảng sau khi đổi dấu:
 [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [11]:
# --- BÀI 11: Tạo ma trận 5x5 có đường chéo chính cho trước ---
print("\n--- Numpy Bài 11 ---")
# Hàm np.diag sẽ tạo ma trận từ một danh sách các phần tử đường chéo
diagonal_values = [1, 2, 3, 4, 5]
matrix_11 = np.diag(diagonal_values)
print("Ma trận 5x5 với đường chéo 1-5:\n", matrix_11)


--- Numpy Bài 11 ---
Ma trận 5x5 với đường chéo 1-5:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Pandas

In [12]:


# --- BÀI 19: Tìm phần tử trong sr1 mà không có trong sr2 ---
print("\n--- Pandas Bài 19 ---")
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
# Dùng hàm isin kết hợp với dấu ~ (phủ định)
result_19 = sr1[~sr1.isin(sr2)]
print("Các phần tử trong sr1 không có trong sr2:\n", result_19)



--- Pandas Bài 19 ---
Các phần tử trong sr1 không có trong sr2:
 0    1
2    3
4    5
dtype: int64


In [13]:

# --- BÀI 29: Lọc dữ liệu theo nhiều điều kiện (Dựa trên exam_data bài 22) ---
print("\n--- Pandas Bài 29 ---")
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
}
df = pd.DataFrame(exam_data)
# Điều kiện: attempt > 2 VÀ score trong khoảng (15, 20)
filtered_df = df[(df['attempts'] > 2) & (df['score'].between(15, 20))]
print("Kết quả lọc (Attempts > 2 & 15 < Score < 20):\n", filtered_df)


--- Pandas Bài 29 ---
Kết quả lọc (Attempts > 2 & 15 < Score < 20):
       name  score  attempts
5  Michael   20.0         3


### Tensor

In [14]:
import tensorflow as tf

# --- BÀI 4: Tạo tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10] ---
print("\n--- Tensor Bài 4 ---")
# Lưu ý: Trong khoảng [5, 10] thì các số chẵn là 6, 8, 10.
# Để có đúng 50 phần tử, ta có thể dùng tf.constant hoặc lặp lại giá trị
even_numbers = [6, 8, 10] * 16 + [6, 8] # Ví dụ tạo đủ 50 phần tử chẵn
tensor_4 = tf.constant(even_numbers)
print("Tensor 50 phần tử chẵn:\n", tensor_4)




--- Tensor Bài 4 ---
Tensor 50 phần tử chẵn:
 tf.Tensor(
[ 6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10
  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10
  6  8], shape=(50,), dtype=int32)


In [15]:
# --- BÀI 10: Logic x + y nếu x < y, ngược lại x - y ---
print("\n--- Tensor Bài 10 ---")
x = tf.random.uniform([5], minval=0, maxval=10)
y = tf.random.uniform([5], minval=0, maxval=10)
# Dùng tf.where để thực hiện logic vector hóa
result_10 = tf.where(x < y, x + y, x - y)
print("x:", x.numpy())
print("y:", y.numpy())
print("Kết quả (x+y if x<y else x-y):\n", result_10.numpy())


--- Tensor Bài 10 ---
x: [6.483918  1.4108813 4.198681  0.5718851 6.1830435]
y: [2.6633203 3.0417013 0.4853487 6.344117  9.127637 ]
Kết quả (x+y if x<y else x-y):
 [ 3.820598   4.4525824  3.7133322  6.9160023 15.31068  ]
